### ISSUE TITLE
Does not detect when camera is rebooted

### ISSUE THREAD

**Issue by rao-subba-venkata** [nayrnet/node-dahua-api#14]
This is a great module. Found one issue with alarm. If the camera is rebooted after the connection, it is not detected. Please suggest a solution or fix.

**Comment by rao-subba-venkata** [comment]
Of course the comment in the code says - Set keep-alive probes - throws ESOCKETTIMEDOUT error after ~16min if connection broken

How do we reduce this timeout ?

**Comment by rao-subba-venkata** [comment]
Tried the following. But, no luck.
      
      NetKeepAlive.setUserTimeout(socket, 10000);
      if (TRACE) console.log('TCP_USER_TIMEOUT:',NetKeepAlive.getUserTimeout(socket));

**Comment by FrankZZ** [comment]
I am working on a fix for this issue. I will open a PR soon
